### ISSUE TITLE
TODO LIST!!!

### ISSUE THREAD

**Issue by urielsv** [urielsv/AmongOS#1]
### OUR TODO LIST!!! 
- [x] Refactor structure drivers and other functionalities @urielsv 
- [x] Remove comments @urielsv 
- [x] Shell functionality @urielsv @feliventu 
- [x] Fix kill & waitpid @urielsv @feliventu 
- [x] Pipes @felitba 
- [x] FDs @felitba 
- [ ] #4
- [x] Fix mutex semaphores @feliventu @urielsv 
- [ ] #3
- [x] Userland commands (cat, ps, etc).
- [ ] #2
_Si me falto agregar algo me avisan y lo ponemos!!_

**Comment by urielsv** [comment]
Missing cat!
